resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    memory: 100Mi 

webhook:                
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

cainjector:                
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi

startupapicheck:                
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 100Mi