controller:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 64Mi
  service:
    enableHttp: false
    enabled: true
    external:
      enabled: true
    targetPorts:
      http: https
      https: https
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
      #service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0e9fe909e0568ed31, subnet-0affab8ba313dd621
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "10254"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/healthz"
      service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: BillingCostCenter=0701-97290010 AGT, Division=gts, Environment=dev, ResourceContact=AGTDevOpsConfigurationAndTraining@transamerica.com, ResourcePurpose=ArgoCD Environment, Application=APM0005100:CICD TOOLS
      service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8, 161.179.0.0/16, 198.39.0.0/16, 162.123.0.0/16, 10.45.72.0/24, 100.64.0.0/16

admissionWebhooks:
  resources:
    requests:
      cpu: 100m
      memory: 20Mi
    limits:
      memory: 40Mi

  patchWebhookJob:
    resources:
      requests:
        cpu: 100m
        memory: 20Mis
      limits:
        memory: 40Mi
